rt-image-viewer: workaround rust regression
Somewhere between
https://github.com/rust-lang/rust/commit/476acbf1e9965b5e95c90f0d7d658709812b7003
and
https://github.com/rust-lang/rust/commit/45b3c28518e4c45dfd12bc2c4400c0d0e9639927
a regression happens which results in:

```
    Processing "rt-image-viewer-frontend-yew.wasm"...
thread 'main' panicked at 'unknown name section chunk type: 7', C:\Users\drand\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-web-0.6.26\src\wasm_context.rs:642:41
```

With a quick look, I couldn't figure out what commit in rust likely was
relevant. Since this seems to involve parsing of wasm output by the
outdated project https://github.com/koute/cargo-web , and since our use
here should be upgraded to modern tools anyway, it is the least work
right now just to build with an older rust compiler and then, in the
future, port everything here to a more modern stack.